<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="QuickFIXn.Core" />
    <PackageReference Include="QuickFIXn.FIX44" />
  </ItemGroup>

  <ItemGroup>
    <None Include="generator.cfg" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\spec\FIX44.xml" Link="FIX44.xml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
